### ISSUE TITLE
Does not install Rust on pre-commit.ci

### ISSUE THREAD

**Issue by djmitche** [FeryET/pre-commit-rust#2]
See https://github.com/GothenburgBitFactory/taskchampion-sync-server/pull/33

How can I cause this to "bootstrap" a cargo/rust install?

**Comment by FeryET** [comment]
Cargo should be installed on your system for this pre-commit hook to work.

**Comment by djmitche** [comment]
This is running on pre-commit.ci, not my system

**Comment by FeryET** [comment]
> This is running on pre-commit.ci, not my system

Cargo (rust) should be installed in the docker image of your CI. Installing another version of cargo for the sole purpose of running a pre-commit hook is rather ill-advised. I can work on using the cargo docker image in the pre-commit hook too, but it might take a while.

**Comment by djmitche** [comment]
This is probably the wrong place to ask. I'm new to using the hosted GitHub app, pre-commit.ci. I don't think I can control the environment there. I'll see if I can figure that out, or maybe just drop the idea.

**Comment by djmitche** [comment]
For anyone with the same question I had, this repo just doesn't support running in pre-commit.ci.
